### ISSUE TITLE
`[AttributeError]: 'list' object has no attribute 'version'` error as of pdm 1.17.0

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/update-deps-action#18]
```
🔒 Lock successful.
/home/runner/.local/share/pdm/venv/lib/python3.10/site-packages/pdm_update_action/__init__.py:56: PDMDeprecationWarning: Project.locked_repository is deprecated, use Project.get_locked_repository() instead
  after_candidates = project.locked_repository.all_candidates
[AttributeError]: 'list' object has no attribute 'version'
WARNING: Add '-v' to see the detailed traceback
Error: Process completed with exit code 1.
```

full log: https://github.com/DetachHead/pytest-robotframework/actions/runs/10005156257/job/27655283243

[job-logs.txt](https://github.com/user-attachments/files/16309646/job-logs.txt)

**Comment by ModeSevenIndustrialSolutions** [comment]
@DetachHead 
I'm seeing this error with one of my repositories? Did this get fixed?

**Comment by frostming** [comment]
Yes, are you using the latest version of the action?

**Comment by ModeSevenIndustrialSolutions** [comment]
Yep, I'm using v1.9, the latest version of the action.
All the affected source code, Github actions/workflows and Python project metadata is here:
https://github.com/os-climate/osc-github-devops/
Here's the reusable workflow that calls the action:
https://github.com/os-climate/osc-github-devops/blob/main/.github/workflows/reuse-dependencies.yaml
Here's the failure:
https://github.com/os-climate/osc-github-devops/actions/runs/12875582088/job/35897151908
In the past I've found issues with the pyproject.toml file format/syntax, but that doesn't seem to apply here.

**Comment by frostming** [comment]
> Yep, I'm using v1.9, the latest version of the action.

Please upgrade to v1.10

**Comment by ModeSevenIndustrialSolutions** [comment]
Somehow missed the updated release. Bumping the version of the actions has fixed it; thanks for the feedback.
