### ISSUE TITLE
DCO and option to have signed-off-by in commit messages

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [pdm-project/update-deps-action#4]
This app is quite widely used by GitHub projects: https://probot.github.io/apps/dco/

Without a "signed-off-by" message in commits, a PR submitted to a repository with this App cannot be merged directly in the GitHub portal. For the "update-deps-action" workflow/action, this creates unnecessary friction to getting the automatically generated pull requests merged. Could we create a new boolean input flag to have this automatically added, the equivalent of passing "-s" for "git commit"? Otherwise we have to pull down the PR and manually amend the commit message. I'm guessing this same outcome could be created by setting the commit message to a multiline message containing the necessary text, but that seems somewhat messy?

**Comment by frostming** [comment]
I don't think this is a hard one to do. So are you willing to contribute?

**Comment by ModeSevenIndustrialSolutions** [comment]
Please see my pull request here: https://github.com/pdm-project/update-deps-action/pull/5
I noticed you were using EndBug and it already has this feature available:
https://github.com/EndBug/add-and-commit
It was just a matter of creating a new boolean flag as an optional input and passing that through at the time the commit message is generated. I have tested this and automatic changes now pass DCO verification when the app is installed in a given project/repo.

**Comment by ModeSevenIndustrialSolutions** [comment]
<img width="1264" alt="image" src="https://github.com/pdm-project/update-deps-action/assets/93649628/9d14f3fd-af9c-4c87-8ecb-d84db5395577">

**Comment by ModeSevenIndustrialSolutions** [comment]
<img width="1257" alt="image" src="https://github.com/pdm-project/update-deps-action/assets/93649628/ad588404-4d86-4145-b2b7-44d35107e0bf">

**Comment by ModeSevenIndustrialSolutions** [comment]
Added some screenshots to show testing/demonstration.
